### PR TITLE
create scrapeHeroData.sh

### PR DESCRIPTION
**Pull request by mrchief**
Scrapes data for a given hero and prepares the yaml format needed for the `<heroes>.yaml` file.

This does the heavy lifting to make it easier to add new heroes. You'll need to tweak a few fields (marked as `<TODO>`) as we don't have a way of mapping those easily yet.

Sample output 

```
> scrapeHeroData Grace

name: Grace
class: Druid
source: <TODO>
speed: Fast
power: 806
attack: 756
defense: 766
health: 1444
skill: Malison of the Wildlands
effects:
  - Deals 285% damage to the target and nearby enemies.
  - The target and nearby enemies cannot cast any new Taunt status effects for 3 turns.
  - The target and nearby enemies get -34% defense against Special Skills for 3 turns.
  - Element Link gives all Nature allies immunity to new Fiends for 4 turns
  - Element Link affects all allies when using 2 or more members of the same family.
types:
  - <TODO>
passives:
  - Resist Burn - This character has innate resistance against Burn.
  - Mana on Taunt - Each time an enemy receives a Taunt status effect this character’s mana is increased by 10% .
image: <TODO>
family: Legends 2022
```

### CODE REVIEW

**Comment by GDIBass** [comment]
This is awesome!  Can we dump this into a folder (let's say util) and have it output to a tmp folder, then update the git ignore file to ignore ./tmp ?

**Comment by shen12** [comment]
Sure thing. Let me make the tweaks

**Comment by mrchief** [comment]
Sure thing! I'll make the tweaks

**Comment by mrchief** [comment]
Done

**Review by GDIBass — APPROVED** [review]

**Comment by GDIBass** [comment]
Lgtm, thank you!  If you want to also push an update to the README noting the option to use this, feel free!

**Pull request merged**
