### PR TITLE
new covenant heroes and families - bonecrusher and mistweaver

### PR DESCRIPTION
**Pull request by exicemrn**

### CODE REVIEW

**Comment by Buffer379x** [comment]
Hey @marian01 ,
Thanks for your help in this project, any support is always good! It looks like we committed our changes almost at the same time. 😄 

If you are willing to help in a long term, maybe we can find a way to organize ourselves so that we do have double the amount of work (e.g. splitting into creating text data, creating images, etc.). Let me know what you think about it  👍 

Greetings.

**Comment by exicemrn** [comment]
> Hey @marian01 , Thanks for your help in this project, any support is always good! It looks like we committed our changes almost at the same time. 😄
> 
> If you are willing to help in a long term, maybe we can find a way to organize ourselves so that we do not have double the amount of work (e.g. splitting into creating text data, creating images, etc.). Let me know what you think about it 👍
> 
> Greetings.

Yep, we need to find a way to communicate, Line fine with you?

**Comment by Buffer379x** [comment]
Of course, LINE is fine with me: Feel free to add me under brankitobonito (will delete this comment once you found me there).

**Review by GDIBass — APPROVED** [review]

**Comment by GDIBass** [comment]
Looks like this has merge conflicts after merging the last PR.  Can you resolve them when you get a moment?

**Comment by GDIBass** [comment]
@Buffer379x @exicemrn - We could also make some changes to make clashes less likely if that would be better.

Maybe something like this:

1. Add a folder for each of the stars for each hero
2. Have each hero put into a file that only has it's data.

So, instead of having all the hero data for each star in one place it would look like:

heroes/blue/5/magni.yml
heroes/blue/5/ariel.yml

This should make merge conflicts a lot easier to resolve.  We could potentially do the same thing for families, and other things too.  Thoughts?

**Comment by exicemrn** [comment]
> @Buffer379x @exicemrn - We could also make some changes to make clashes less likely if that would be better.
> 
> Maybe something like this:
> 
> 1. Add a folder for each of the stars for each hero
> 2. Have each hero put into a file that only has it's data.
> 
> So, instead of having all the hero data for each star in one place it would look like:
> 
> heroes/blue/5/magni.yml heroes/blue/5/ariel.yml
> 
> This should make merge conflicts a lot easier to resolve. We could potentially do the same thing for families, and other things too. Thoughts?

yep, we can do that.

**Comment by Buffer379x** [comment]
@GDIBass : For the last part I totally agree with you, it should be easier to point out conflicts via single files rather than looking through one whole file.

- Your idea with the single hero files is welcome of course. I will adopt to that workflow since I am currently making all changes at once and create just one commit / pull request. But that is of course the smallest problem. Is this restructure something we will do or do you have some automatism script for it ready?

- For single family files it can be a problem regarding the unique ID. Or will it still be visible at first sight which ID to take for a new family?

Additional idea: Can be used afterwards also to create some sort of hero / family template file for new contributors.

Greetings

**Comment by GDIBass** [comment]
I'll do it via automation.  Definitely don't want you guys to have to go through and do it.

ON IDSs Yeah that was the idea with the naming: <id>-<name>.yml makes sure you can see the next available IDs for new families.

Oh I really like that idea!  So basically have a <template>.yml for each type and the instructions will be to copy that template to a new file and fill everything in?

**Comment by GDIBass** [comment]
@Buffer379x - here's what I was thinking: https://github.com/GDIBass/heroplan_data/pull/48

**Comment by Buffer379x** [comment]
Exactly. Just an imagination:

_template.yaml

#Use this file for creating new heroes. Rename the filename to as the heroes name. E.g. Richard.yaml
-name: [Hero Name]
 class: [Monk | Barbarian | Cleric ...]
 source: [Avalon | Corelia | ...]
 speed: [very slow | slow | average | fast | very fast]
 etc.

**Comment by GDIBass** [comment]
Yeah that's a great idea!

**Pull request closed without merging**
