### PR TITLE
Aether Images

### PR DESCRIPTION
**Pull request by Buffer379x**
Added Lvl 1 - 3 Aether

- It was very difficult to create transparent images of the aether itself as you did it with the ascension material. There is hardly any source material to use nor did my screenshots with a high dpi end up in proper results. 
- I decided to to create it with a layer border and the background fade which is used in the app as well.
- Used PSD (universal) format since I created the images with a different software than GIMP (can be imported into GIMP though).

### CODE REVIEW

**Comment by Buffer379x** [comment]
Tried that, also in GIMP (e.g. the function "Color to Alpha"), but no matter with how I was dealing with the settings, it also made the inner part of the aether transparent or created a very strange cutout. Even when playing around with the selection tool to exclude areas, it looked kind of cheap 🤣 ...
For explanation: the background fade is from the game / screenshot, so it was not manually added afterwards. So the only option is to delete the color for making it transparent.

You can of course give it a try, maybe I am missing something and can learn something new 😄

**Review by GDIBass — APPROVED** [review]
Hah cool.  Going to merge for now.  Will take a crack at it at some point maybe.

I suppose transparency isn’t strictly required for them anyways.

**Comment by Buffer379x** [comment]
@GDIBass : I have been working on the transparency and used a couple of different methods (very time consuming) but I think the result is quite ok. What do you think? Should I continue with the rest or do you want to stick with the "quick n dirty" ones I posted before?
I attached a transparent version as well as a version with a black background (which shows how it most probably will look on heroplan.io).

Greetings

darkaether1_black
darkaether1_transparent
darkaether3_black
darkaether3_transparent

**Comment by GDIBass** [comment]
@Buffer379x - I think either is fine for now.  Feel free to upload what you have and I can use that.

FYI - taking a bit of a break from the rework for my birthday, so it might be some time before I can get these in.

**Comment by Buffer379x** [comment]
> @Buffer379x - I think either is fine for now. Feel free to upload what you have and I can use that.
> 
> FYI - taking a bit of a break from the rework for my birthday, so it might be some time before I can get these in.

No problem, will do. In that case also a happy birthday from me. Enjoy your special day and some time off :)

**Pull request merged**
