### PR TITLE
docs: add info about hero scrapper script 📚

### PR DESCRIPTION
**Pull request by mrchief**

### CODE REVIEW

**Comment by mrchief** [comment]
@GDIBass feel free to make changes to the readme as you deem fit

**Comment by mrchief** [comment]
@GDIBass now it also scrapes the hero image so saves a ton of time with image manipulation. 

We can automate a lot of this process with a github action. It can take the hero name as an input, do the scraping and create a PR. All that'll be left is filling the `todos`, doing a QA and merging the PR.

**Review by GDIBass — APPROVED** [review]

**Comment by GDIBass** [comment]
lgtm!  Thank you!

**Comment by mrchief** [comment]
@GDIBass Do you have a slack/discord/other IM tool of choice? I pinged you on line but I don't think you're active there.

**Pull request merged**
